"""
Streamlit dashboard for exploring the sensor data, detected anomalies, and
generated incident reports.

Run:
    streamlit run src/dashboard.py
"""
import json
import os

import pandas as pd
import streamlit as st

from features import load_series, build_features
from detect import run_detection
from evaluate import extract_events

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_CSV = os.path.join(ROOT, "data", "machine_temperature_system_failure.csv")
LABELS_JSON = os.path.join(ROOT, "data", "combined_labels.json")
REPORTS_DIR = os.path.join(ROOT, "reports")
LABEL_KEY = "realKnownCause/machine_temperature_system_failure.csv"

st.set_page_config(page_title="Sensor Anomaly Detection", layout="wide")
st.title("Sensor Anomaly Detection & LLM Incident Reports")
st.caption(
    "Real NAB machine-temperature dataset · Isolation Forest anomaly detection · "
    "incident reports generated by a local Ollama LLM (falls back to a labeled "
    "template if Ollama isn't running)"
)


@st.cache_data
def load_and_detect():
    df = load_series(DATA_CSV)
    feat = build_features(df)
    result = run_detection(feat)
    with open(LABELS_JSON) as f:
        ground_truth = json.load(f)[LABEL_KEY]
    return result, ground_truth


result, ground_truth = load_and_detect()
merge_gap = pd.Timedelta(hours=6)
events = extract_events(result, "is_anomaly", merge_gap=merge_gap)

col1, col2, col3 = st.columns(3)
col1.metric("Sensor readings", f"{len(result):,}")
col2.metric("Anomaly events detected", len(events))
col3.metric("Ground-truth labeled failures", len(ground_truth))

st.subheader("Sensor reading over time")
chart_df = result.set_index("timestamp")[["value"]].copy()
st.line_chart(chart_df)

st.subheader("Detected anomaly events")
if events:
    ev_df = pd.DataFrame(events)
    st.dataframe(ev_df, use_container_width=True)
else:
    st.info("No anomaly events detected.")

st.subheader("Ground-truth labeled failure timestamps")
st.write(ground_truth)

report_path = os.path.join(REPORTS_DIR, "incident_reports.md")
st.subheader("Generated incident reports")
if os.path.exists(report_path):
    with open(report_path) as f:
        st.markdown(f.read())
else:
    st.info("Run `python3 src/main.py` first to generate incident_reports.md.")

eval_path = os.path.join(REPORTS_DIR, "evaluation_report.json")
st.subheader("Evaluation metrics")
if os.path.exists(eval_path):
    with open(eval_path) as f:
        metrics = json.load(f)
    st.json(metrics)
else:
    st.info("Run `python3 src/main.py` first to generate evaluation_report.json.")
